// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

// CreateProductsGroupsByProductPathParamProduct - Cribl Product
type CreateProductsGroupsByProductPathParamProduct string

const (
	CreateProductsGroupsByProductPathParamProductStream CreateProductsGroupsByProductPathParamProduct = "stream"
	CreateProductsGroupsByProductPathParamProductEdge   CreateProductsGroupsByProductPathParamProduct = "edge"
)

func (e CreateProductsGroupsByProductPathParamProduct) ToPointer() *CreateProductsGroupsByProductPathParamProduct {
	return &e
}
func (e *CreateProductsGroupsByProductPathParamProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		*e = CreateProductsGroupsByProductPathParamProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateProductsGroupsByProductPathParamProduct: %v", v)
	}
}

type CreateProductsGroupsByProductRequest struct {
	// Cribl Product
	Product CreateProductsGroupsByProductPathParamProduct `pathParam:"style=simple,explode=false,name=product"`
	// ConfigGroup object
	ConfigGroup shared.ConfigGroup `request:"mediaType=application/json"`
}

func (o *CreateProductsGroupsByProductRequest) GetProduct() CreateProductsGroupsByProductPathParamProduct {
	if o == nil {
		return CreateProductsGroupsByProductPathParamProduct("")
	}
	return o.Product
}

func (o *CreateProductsGroupsByProductRequest) GetConfigGroup() shared.ConfigGroup {
	if o == nil {
		return shared.ConfigGroup{}
	}
	return o.ConfigGroup
}

// CreateProductsGroupsByProductResponseBody - a list of ConfigGroup objects
type CreateProductsGroupsByProductResponseBody struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []shared.ConfigGroup `json:"items,omitempty"`
}

func (o *CreateProductsGroupsByProductResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *CreateProductsGroupsByProductResponseBody) GetItems() []shared.ConfigGroup {
	if o == nil {
		return nil
	}
	return o.Items
}

type CreateProductsGroupsByProductResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of ConfigGroup objects
	Object *CreateProductsGroupsByProductResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *CreateProductsGroupsByProductResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateProductsGroupsByProductResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateProductsGroupsByProductResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateProductsGroupsByProductResponse) GetObject() *CreateProductsGroupsByProductResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *CreateProductsGroupsByProductResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
