// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

// GetProductsUsersByProductPathParamProduct - product by which to filter members
type GetProductsUsersByProductPathParamProduct string

const (
	GetProductsUsersByProductPathParamProductStream GetProductsUsersByProductPathParamProduct = "stream"
	GetProductsUsersByProductPathParamProductEdge   GetProductsUsersByProductPathParamProduct = "edge"
	GetProductsUsersByProductPathParamProductSearch GetProductsUsersByProductPathParamProduct = "search"
	GetProductsUsersByProductPathParamProductLake   GetProductsUsersByProductPathParamProduct = "lake"
)

func (e GetProductsUsersByProductPathParamProduct) ToPointer() *GetProductsUsersByProductPathParamProduct {
	return &e
}
func (e *GetProductsUsersByProductPathParamProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		fallthrough
	case "search":
		fallthrough
	case "lake":
		*e = GetProductsUsersByProductPathParamProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetProductsUsersByProductPathParamProduct: %v", v)
	}
}

type GetProductsUsersByProductRequest struct {
	// product by which to filter members
	Product GetProductsUsersByProductPathParamProduct `pathParam:"style=simple,explode=false,name=product"`
	// filter to specific group by groupId
	GroupID *string `queryParam:"style=form,explode=true,name=groupId"`
}

func (o *GetProductsUsersByProductRequest) GetProduct() GetProductsUsersByProductPathParamProduct {
	if o == nil {
		return GetProductsUsersByProductPathParamProduct("")
	}
	return o.Product
}

func (o *GetProductsUsersByProductRequest) GetGroupID() *string {
	if o == nil {
		return nil
	}
	return o.GroupID
}

// GetProductsUsersByProductResponseBody - a list of User objects
type GetProductsUsersByProductResponseBody struct {
	// number of items present in the items array
	Count *int64        `json:"count,omitempty"`
	Items []shared.User `json:"items,omitempty"`
}

func (o *GetProductsUsersByProductResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetProductsUsersByProductResponseBody) GetItems() []shared.User {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetProductsUsersByProductResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of User objects
	Object *GetProductsUsersByProductResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetProductsUsersByProductResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetProductsUsersByProductResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetProductsUsersByProductResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetProductsUsersByProductResponse) GetObject() *GetProductsUsersByProductResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetProductsUsersByProductResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
