// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

type GetPipelineByIDRequest struct {
	// Unique ID to GET
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetPipelineByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetPipelineByIDResponseBody - a list of Pipeline objects
type GetPipelineByIDResponseBody struct {
	// number of items present in the items array
	Count *int64            `json:"count,omitempty"`
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (o *GetPipelineByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetPipelineByIDResponseBody) GetItems() []shared.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetPipelineByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *GetPipelineByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetPipelineByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPipelineByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPipelineByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPipelineByIDResponse) GetObject() *GetPipelineByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetPipelineByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
