// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

// QueryParamMode - Export mode. Note: "merge_safe" is deprecated and will be removed in v5.0.0. Use "merge" instead.
type QueryParamMode string

const (
	QueryParamModeMerge       QueryParamMode = "merge"
	QueryParamModeDefaultOnly QueryParamMode = "default_only"
	QueryParamModeMergeSafe   QueryParamMode = "merge_safe"
)

func (e QueryParamMode) ToPointer() *QueryParamMode {
	return &e
}
func (e *QueryParamMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "merge":
		fallthrough
	case "default_only":
		fallthrough
	case "merge_safe":
		*e = QueryParamMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamMode: %v", v)
	}
}

type GetPacksExportByIDRequest struct {
	// Pack name
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Export mode. Note: "merge_safe" is deprecated and will be removed in v5.0.0. Use "merge" instead.
	Mode QueryParamMode `queryParam:"style=form,explode=true,name=mode"`
	// Filename of the exported Pack
	Filename *string `queryParam:"style=form,explode=true,name=filename"`
}

func (o *GetPacksExportByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetPacksExportByIDRequest) GetMode() QueryParamMode {
	if o == nil {
		return QueryParamMode("")
	}
	return o.Mode
}

func (o *GetPacksExportByIDRequest) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

// GetPacksExportByIDResponseBody - a list of any objects
type GetPacksExportByIDResponseBody struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []map[string]any `json:"items,omitempty"`
}

func (o *GetPacksExportByIDResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetPacksExportByIDResponseBody) GetItems() []map[string]any {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetPacksExportByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of any objects
	Object *GetPacksExportByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetPacksExportByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPacksExportByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPacksExportByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPacksExportByIDResponse) GetObject() *GetPacksExportByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetPacksExportByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
