// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

// GetProductsGroupsByProductPathParamProduct - Cribl Product
type GetProductsGroupsByProductPathParamProduct string

const (
	GetProductsGroupsByProductPathParamProductStream GetProductsGroupsByProductPathParamProduct = "stream"
	GetProductsGroupsByProductPathParamProductEdge   GetProductsGroupsByProductPathParamProduct = "edge"
)

func (e GetProductsGroupsByProductPathParamProduct) ToPointer() *GetProductsGroupsByProductPathParamProduct {
	return &e
}
func (e *GetProductsGroupsByProductPathParamProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		*e = GetProductsGroupsByProductPathParamProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetProductsGroupsByProductPathParamProduct: %v", v)
	}
}

type GetProductsGroupsByProductRequest struct {
	// fields to add to results: git.commit, git.localChanges, git.log
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// Cribl Product
	Product GetProductsGroupsByProductPathParamProduct `pathParam:"style=simple,explode=false,name=product"`
}

func (o *GetProductsGroupsByProductRequest) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *GetProductsGroupsByProductRequest) GetProduct() GetProductsGroupsByProductPathParamProduct {
	if o == nil {
		return GetProductsGroupsByProductPathParamProduct("")
	}
	return o.Product
}

// GetProductsGroupsByProductResponseBody - a list of ConfigGroup objects
type GetProductsGroupsByProductResponseBody struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []shared.ConfigGroup `json:"items,omitempty"`
}

func (o *GetProductsGroupsByProductResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetProductsGroupsByProductResponseBody) GetItems() []shared.ConfigGroup {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetProductsGroupsByProductResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of ConfigGroup objects
	Object *GetProductsGroupsByProductResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetProductsGroupsByProductResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetProductsGroupsByProductResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetProductsGroupsByProductResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetProductsGroupsByProductResponse) GetObject() *GetProductsGroupsByProductResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetProductsGroupsByProductResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
