// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/models/shared"
	"net/http"
)

// Product - filter teams by product
type Product string

const (
	ProductStream Product = "stream"
	ProductEdge   Product = "edge"
	ProductSearch Product = "search"
)

func (e Product) ToPointer() *Product {
	return &e
}
func (e *Product) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		fallthrough
	case "search":
		*e = Product(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Product: %v", v)
	}
}

type GetTeamRequest struct {
	// filter teams by product
	Product *Product `queryParam:"style=form,explode=true,name=product"`
}

func (o *GetTeamRequest) GetProduct() *Product {
	if o == nil {
		return nil
	}
	return o.Product
}

// GetTeamResponseBody - a list of Team objects
type GetTeamResponseBody struct {
	// number of items present in the items array
	Count *int64        `json:"count,omitempty"`
	Items []shared.Team `json:"items,omitempty"`
}

func (o *GetTeamResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GetTeamResponseBody) GetItems() []shared.Team {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Team objects
	Object *GetTeamResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetTeamResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTeamResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTeamResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTeamResponse) GetObject() *GetTeamResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetTeamResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
