// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

type CriblTerraformBilling struct {
	Invoices    *Invoices
	Consumption *Consumption

	sdkConfiguration sdkConfiguration
}

func newCriblTerraformBilling(sdkConfig sdkConfiguration) *CriblTerraformBilling {
	return &CriblTerraformBilling{
		sdkConfiguration: sdkConfig,
		Invoices:         newInvoices(sdkConfig),
		Consumption:      newConsumption(sdkConfig),
	}
}
