// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdk

type V5 struct {
	Billing *CriblTerraformBilling

	sdkConfiguration sdkConfiguration
}

func newV5(sdkConfig sdkConfiguration) *V5 {
	return &V5{
		sdkConfiguration: sdkConfig,
		Billing:          newCriblTerraformBilling(sdkConfig),
	}
}
