// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/internal/utils"
)

type PipelineGroups struct {
	Name string `json:"name"`
	// Short description of this group
	Description *string `json:"description,omitempty"`
	// Whether this group is disabled
	Disabled *bool `json:"disabled,omitempty"`
}

func (o *PipelineGroups) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PipelineGroups) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PipelineGroups) GetDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.Disabled
}

type Conf struct {
	// Time (in ms) to wait for an async function to complete processing of a data item
	AsyncFuncTimeout *int64 `json:"asyncFuncTimeout,omitempty"`
	// The output destination for events processed by this Pipeline
	Output      *string `default:"default" json:"output"`
	Description *string `json:"description,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// List of Functions to pass data through
	Functions []PipelineFunctionConf    `json:"functions,omitempty"`
	Groups    map[string]PipelineGroups `json:"groups,omitempty"`
}

func (c Conf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Conf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Conf) GetAsyncFuncTimeout() *int64 {
	if o == nil {
		return nil
	}
	return o.AsyncFuncTimeout
}

func (o *Conf) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *Conf) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Conf) GetStreamtags() []string {
	if o == nil {
		return nil
	}
	return o.Streamtags
}

func (o *Conf) GetFunctions() []PipelineFunctionConf {
	if o == nil {
		return nil
	}
	return o.Functions
}

func (o *Conf) GetGroups() map[string]PipelineGroups {
	if o == nil {
		return nil
	}
	return o.Groups
}

type Pipeline struct {
	ID   string `json:"id"`
	Conf Conf   `json:"conf"`
}

func (o *Pipeline) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Pipeline) GetConf() Conf {
	if o == nil {
		return Conf{}
	}
	return o.Conf
}
