// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Packages struct {
	// Package HTTP URL or local path
	PackageURL string `json:"packageUrl"`
	// Package's MD5 or SHA256 hash HTTP URL or local path
	PackageHashURL *string `json:"packageHashUrl,omitempty"`
}

func (o *Packages) GetPackageURL() string {
	if o == nil {
		return ""
	}
	return o.PackageURL
}

func (o *Packages) GetPackageHashURL() *string {
	if o == nil {
		return nil
	}
	return o.PackageHashURL
}

type UpgradeMasterRequest struct {
	// Provide your own URLs or local paths for platform-specific Cribl packages
	Packages []Packages `json:"packages,omitempty"`
}

func (o *UpgradeMasterRequest) GetPackages() []Packages {
	if o == nil {
		return nil
	}
	return o.Packages
}
