// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AuthTokensExt struct {
	Description types.String                     `tfsdk:"description"`
	Metadata    []InputHTTPAuthTokensExtMetadata `tfsdk:"metadata"`
	Token       types.String                     `tfsdk:"token"`
}
