// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Custom struct {
	CPU     *CPU                      `tfsdk:"cpu"`
	Disk    *Disk                     `tfsdk:"disk"`
	Memory  *InputSystemMetricsMemory `tfsdk:"memory"`
	Network *Network                  `tfsdk:"network"`
	System  *InputSystemMetricsSystem `tfsdk:"system"`
}
