// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type IngestIfNotExists struct {
	Value types.String `tfsdk:"value"`
}
