// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type InputGrafana struct {
	One *InputGrafana1 `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two *InputGrafana2 `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
}
