// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputElastic struct {
	ActivityLogSampleRate types.Number                       `tfsdk:"activity_log_sample_rate"`
	APIVersion            types.String                       `tfsdk:"api_version"`
	AuthTokens            []types.String                     `tfsdk:"auth_tokens"`
	AuthType              types.String                       `tfsdk:"auth_type"`
	CaptureHeaders        types.Bool                         `tfsdk:"capture_headers"`
	Connections           []InputElasticConnections          `tfsdk:"connections"`
	CredentialsSecret     types.String                       `tfsdk:"credentials_secret"`
	CustomAPIVersion      types.String                       `tfsdk:"custom_api_version"`
	Description           types.String                       `tfsdk:"description"`
	Disabled              types.Bool                         `tfsdk:"disabled"`
	ElasticAPI            types.String                       `tfsdk:"elastic_api"`
	EnableHealthCheck     types.Bool                         `tfsdk:"enable_health_check"`
	EnableProxyHeader     types.Bool                         `tfsdk:"enable_proxy_header"`
	Environment           types.String                       `tfsdk:"environment"`
	ExtraHTTPHeaders      []ExtraHTTPHeaders                 `tfsdk:"extra_http_headers"`
	Host                  types.String                       `tfsdk:"host"`
	ID                    types.String                       `tfsdk:"id"`
	IgnoreStandardHeaders types.Bool                         `tfsdk:"ignore_standard_headers"`
	IPAllowlistRegex      types.String                       `tfsdk:"ip_allowlist_regex"`
	IPDenylistRegex       types.String                       `tfsdk:"ip_denylist_regex"`
	KeepAliveTimeout      types.Number                       `tfsdk:"keep_alive_timeout"`
	MaxActiveReq          types.Number                       `tfsdk:"max_active_req"`
	MaxRequestsPerSocket  types.Int64                        `tfsdk:"max_requests_per_socket"`
	Metadata              []InputElasticMetadata             `tfsdk:"metadata"`
	Password              types.String                       `tfsdk:"password"`
	Pipeline              types.String                       `tfsdk:"pipeline"`
	Port                  types.Number                       `tfsdk:"port"`
	Pq                    *InputElasticPq                    `tfsdk:"pq"`
	PqEnabled             types.Bool                         `tfsdk:"pq_enabled"`
	ProxyMode             *ProxyMode                         `tfsdk:"proxy_mode"`
	RequestTimeout        types.Number                       `tfsdk:"request_timeout"`
	SendToRoutes          types.Bool                         `tfsdk:"send_to_routes"`
	SocketTimeout         types.Number                       `tfsdk:"socket_timeout"`
	Streamtags            []types.String                     `tfsdk:"streamtags"`
	TLS                   *InputElasticTLSSettingsServerSide `tfsdk:"tls"`
	Type                  types.String                       `tfsdk:"type"`
	Username              types.String                       `tfsdk:"username"`
}
