// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputConfluentCloud struct {
	AuthenticationTimeout     types.Number                                          `tfsdk:"authentication_timeout"`
	AutoCommitInterval        types.Number                                          `tfsdk:"auto_commit_interval"`
	AutoCommitThreshold       types.Number                                          `tfsdk:"auto_commit_threshold"`
	BackoffRate               types.Number                                          `tfsdk:"backoff_rate"`
	Brokers                   []types.String                                        `tfsdk:"brokers"`
	Connections               []InputConfluentCloudConnections                      `tfsdk:"connections"`
	ConnectionTimeout         types.Number                                          `tfsdk:"connection_timeout"`
	Description               types.String                                          `tfsdk:"description"`
	Disabled                  types.Bool                                            `tfsdk:"disabled"`
	Environment               types.String                                          `tfsdk:"environment"`
	FromBeginning             types.Bool                                            `tfsdk:"from_beginning"`
	GroupID                   types.String                                          `tfsdk:"group_id"`
	HeartbeatInterval         types.Number                                          `tfsdk:"heartbeat_interval"`
	ID                        types.String                                          `tfsdk:"id"`
	InitialBackoff            types.Number                                          `tfsdk:"initial_backoff"`
	KafkaSchemaRegistry       *InputConfluentCloudKafkaSchemaRegistryAuthentication `tfsdk:"kafka_schema_registry"`
	MaxBackOff                types.Number                                          `tfsdk:"max_back_off"`
	MaxBytes                  types.Number                                          `tfsdk:"max_bytes"`
	MaxBytesPerPartition      types.Number                                          `tfsdk:"max_bytes_per_partition"`
	MaxRetries                types.Number                                          `tfsdk:"max_retries"`
	MaxSocketErrors           types.Number                                          `tfsdk:"max_socket_errors"`
	Metadata                  []InputConfluentCloudMetadata                         `tfsdk:"metadata"`
	Pipeline                  types.String                                          `tfsdk:"pipeline"`
	Pq                        *InputConfluentCloudPq                                `tfsdk:"pq"`
	PqEnabled                 types.Bool                                            `tfsdk:"pq_enabled"`
	ReauthenticationThreshold types.Number                                          `tfsdk:"reauthentication_threshold"`
	RebalanceTimeout          types.Number                                          `tfsdk:"rebalance_timeout"`
	RequestTimeout            types.Number                                          `tfsdk:"request_timeout"`
	Sasl                      *InputConfluentCloudAuthentication                    `tfsdk:"sasl"`
	SendToRoutes              types.Bool                                            `tfsdk:"send_to_routes"`
	SessionTimeout            types.Number                                          `tfsdk:"session_timeout"`
	Streamtags                []types.String                                        `tfsdk:"streamtags"`
	TLS                       *InputConfluentCloudTLSSettingsClientSide             `tfsdk:"tls"`
	Topics                    []types.String                                        `tfsdk:"topics"`
	Type                      types.String                                          `tfsdk:"type"`
}
