// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputAzureBlob struct {
	AuthType                    types.String                `tfsdk:"auth_type"`
	BreakerRulesets             []types.String              `tfsdk:"breaker_rulesets"`
	Certificate                 *InputAzureBlobCertificate  `tfsdk:"certificate"`
	ClientID                    types.String                `tfsdk:"client_id"`
	ClientTextSecret            types.String                `tfsdk:"client_text_secret"`
	Connections                 []InputAzureBlobConnections `tfsdk:"connections"`
	ConnectionString            types.String                `tfsdk:"connection_string"`
	Description                 types.String                `tfsdk:"description"`
	Disabled                    types.Bool                  `tfsdk:"disabled"`
	EndpointSuffix              types.String                `tfsdk:"endpoint_suffix"`
	Environment                 types.String                `tfsdk:"environment"`
	FileFilter                  types.String                `tfsdk:"file_filter"`
	ID                          types.String                `tfsdk:"id"`
	MaxMessages                 types.Number                `tfsdk:"max_messages"`
	Metadata                    []InputAzureBlobMetadata    `tfsdk:"metadata"`
	NumReceivers                types.Number                `tfsdk:"num_receivers"`
	ParquetChunkDownloadTimeout types.Number                `tfsdk:"parquet_chunk_download_timeout"`
	ParquetChunkSizeMB          types.Number                `tfsdk:"parquet_chunk_size_mb"`
	Pipeline                    types.String                `tfsdk:"pipeline"`
	Pq                          *InputAzureBlobPq           `tfsdk:"pq"`
	PqEnabled                   types.Bool                  `tfsdk:"pq_enabled"`
	QueueName                   types.String                `tfsdk:"queue_name"`
	SendToRoutes                types.Bool                  `tfsdk:"send_to_routes"`
	ServicePeriodSecs           types.Number                `tfsdk:"service_period_secs"`
	SkipOnError                 types.Bool                  `tfsdk:"skip_on_error"`
	StaleChannelFlushMs         types.Number                `tfsdk:"stale_channel_flush_ms"`
	StorageAccountName          types.String                `tfsdk:"storage_account_name"`
	Streamtags                  []types.String              `tfsdk:"streamtags"`
	TenantID                    types.String                `tfsdk:"tenant_id"`
	TextSecret                  types.String                `tfsdk:"text_secret"`
	Type                        types.String                `tfsdk:"type"`
	VisibilityTimeout           types.Number                `tfsdk:"visibility_timeout"`
}
