// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type Input struct {
	InputAppscope             *InputAppscope             `queryParam:"inline" tfsdk:"input_appscope" tfPlanOnly:"true"`
	InputAzureBlob            *InputAzureBlob            `queryParam:"inline" tfsdk:"input_azure_blob" tfPlanOnly:"true"`
	InputCollection           *InputCollection           `queryParam:"inline" tfsdk:"input_collection" tfPlanOnly:"true"`
	InputConfluentCloud       *InputConfluentCloud       `queryParam:"inline" tfsdk:"input_confluent_cloud" tfPlanOnly:"true"`
	InputCribl                *InputCribl                `queryParam:"inline" tfsdk:"input_cribl" tfPlanOnly:"true"`
	InputCriblHTTP            *InputCriblHTTP            `queryParam:"inline" tfsdk:"input_cribl_http" tfPlanOnly:"true"`
	InputCriblmetrics         *InputCriblmetrics         `queryParam:"inline" tfsdk:"input_criblmetrics" tfPlanOnly:"true"`
	InputCriblTCP             *InputCriblTCP             `queryParam:"inline" tfsdk:"input_cribl_tcp" tfPlanOnly:"true"`
	InputCrowdstrike          *InputCrowdstrike          `queryParam:"inline" tfsdk:"input_crowdstrike" tfPlanOnly:"true"`
	InputDatadogAgent         *InputDatadogAgent         `queryParam:"inline" tfsdk:"input_datadog_agent" tfPlanOnly:"true"`
	InputDatagen              *InputDatagen              `queryParam:"inline" tfsdk:"input_datagen" tfPlanOnly:"true"`
	InputEdgePrometheus       *InputEdgePrometheus       `queryParam:"inline" tfsdk:"input_edge_prometheus" tfPlanOnly:"true"`
	InputElastic              *InputElastic              `queryParam:"inline" tfsdk:"input_elastic" tfPlanOnly:"true"`
	InputEventhub             *InputEventhub             `queryParam:"inline" tfsdk:"input_eventhub" tfPlanOnly:"true"`
	InputExec                 *InputExec                 `queryParam:"inline" tfsdk:"input_exec" tfPlanOnly:"true"`
	InputFile                 *InputFile                 `queryParam:"inline" tfsdk:"input_file" tfPlanOnly:"true"`
	InputFirehose             *InputFirehose             `queryParam:"inline" tfsdk:"input_firehose" tfPlanOnly:"true"`
	InputGooglePubsub         *InputGooglePubsub         `queryParam:"inline" tfsdk:"input_google_pubsub" tfPlanOnly:"true"`
	InputGrafana              *InputGrafana              `queryParam:"inline" tfsdk:"input_grafana" tfPlanOnly:"true"`
	InputHTTP                 *InputHTTP                 `queryParam:"inline" tfsdk:"input_http" tfPlanOnly:"true"`
	InputHTTPRaw              *InputHTTPRaw              `queryParam:"inline" tfsdk:"input_http_raw" tfPlanOnly:"true"`
	InputJournalFiles         *InputJournalFiles         `queryParam:"inline" tfsdk:"input_journal_files" tfPlanOnly:"true"`
	InputKafka                *InputKafka                `queryParam:"inline" tfsdk:"input_kafka" tfPlanOnly:"true"`
	InputKinesis              *InputKinesis              `queryParam:"inline" tfsdk:"input_kinesis" tfPlanOnly:"true"`
	InputKubeEvents           *InputKubeEvents           `queryParam:"inline" tfsdk:"input_kube_events" tfPlanOnly:"true"`
	InputKubeLogs             *InputKubeLogs             `queryParam:"inline" tfsdk:"input_kube_logs" tfPlanOnly:"true"`
	InputKubeMetrics          *InputKubeMetrics          `queryParam:"inline" tfsdk:"input_kube_metrics" tfPlanOnly:"true"`
	InputLoki                 *InputLoki                 `queryParam:"inline" tfsdk:"input_loki" tfPlanOnly:"true"`
	InputMetrics              *InputMetrics              `queryParam:"inline" tfsdk:"input_metrics" tfPlanOnly:"true"`
	InputModelDrivenTelemetry *InputModelDrivenTelemetry `queryParam:"inline" tfsdk:"input_model_driven_telemetry" tfPlanOnly:"true"`
	InputMsk                  *InputMsk                  `queryParam:"inline" tfsdk:"input_msk" tfPlanOnly:"true"`
	InputNetflow              *InputNetflow              `queryParam:"inline" tfsdk:"input_netflow" tfPlanOnly:"true"`
	InputOffice365Mgmt        *InputOffice365Mgmt        `queryParam:"inline" tfsdk:"input_office365_mgmt" tfPlanOnly:"true"`
	InputOffice365MsgTrace    *InputOffice365MsgTrace    `queryParam:"inline" tfsdk:"input_office365_msg_trace" tfPlanOnly:"true"`
	InputOffice365Service     *InputOffice365Service     `queryParam:"inline" tfsdk:"input_office365_service" tfPlanOnly:"true"`
	InputOpenTelemetry        *InputOpenTelemetry        `queryParam:"inline" tfsdk:"input_open_telemetry" tfPlanOnly:"true"`
	InputPrometheus           *InputPrometheus           `queryParam:"inline" tfsdk:"input_prometheus" tfPlanOnly:"true"`
	InputPrometheusRw         *InputPrometheusRw         `queryParam:"inline" tfsdk:"input_prometheus_rw" tfPlanOnly:"true"`
	InputRawUDP               *InputRawUDP               `queryParam:"inline" tfsdk:"input_raw_udp" tfPlanOnly:"true"`
	InputS3                   *InputS3                   `queryParam:"inline" tfsdk:"input_s3" tfPlanOnly:"true"`
	InputS3Inventory          *InputS3Inventory          `queryParam:"inline" tfsdk:"input_s3_inventory" tfPlanOnly:"true"`
	InputSecurityLake         *InputSecurityLake         `queryParam:"inline" tfsdk:"input_security_lake" tfPlanOnly:"true"`
	InputSnmp                 *InputSnmp                 `queryParam:"inline" tfsdk:"input_snmp" tfPlanOnly:"true"`
	InputSplunk               *InputSplunk               `queryParam:"inline" tfsdk:"input_splunk" tfPlanOnly:"true"`
	InputSplunkHec            *InputSplunkHec            `queryParam:"inline" tfsdk:"input_splunk_hec" tfPlanOnly:"true"`
	InputSplunkSearch         *InputSplunkSearch         `queryParam:"inline" tfsdk:"input_splunk_search" tfPlanOnly:"true"`
	InputSqs                  *InputSqs                  `queryParam:"inline" tfsdk:"input_sqs" tfPlanOnly:"true"`
	InputSyslog               *InputSyslog               `queryParam:"inline" tfsdk:"input_syslog" tfPlanOnly:"true"`
	InputSystemMetrics        *InputSystemMetrics        `queryParam:"inline" tfsdk:"input_system_metrics" tfPlanOnly:"true"`
	InputSystemState          *InputSystemState          `queryParam:"inline" tfsdk:"input_system_state" tfPlanOnly:"true"`
	InputTCP                  *InputTCP                  `queryParam:"inline" tfsdk:"input_tcp" tfPlanOnly:"true"`
	InputTcpjson              *InputTcpjson              `queryParam:"inline" tfsdk:"input_tcpjson" tfPlanOnly:"true"`
	InputWef                  *InputWef                  `queryParam:"inline" tfsdk:"input_wef" tfPlanOnly:"true"`
	InputWindowsMetrics       *InputWindowsMetrics       `queryParam:"inline" tfsdk:"input_windows_metrics" tfPlanOnly:"true"`
	InputWinEventLogs         *InputWinEventLogs         `queryParam:"inline" tfsdk:"input_win_event_logs" tfPlanOnly:"true"`
	InputWiz                  *InputWiz                  `queryParam:"inline" tfsdk:"input_wiz" tfPlanOnly:"true"`
	InputZscalerHec           *InputZscalerHec           `queryParam:"inline" tfsdk:"input_zscaler_hec" tfPlanOnly:"true"`
}
