// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputSplunkHec struct {
	AccessControlAllowHeaders []types.String                       `tfsdk:"access_control_allow_headers"`
	AccessControlAllowOrigin  []types.String                       `tfsdk:"access_control_allow_origin"`
	ActivityLogSampleRate     types.Number                         `tfsdk:"activity_log_sample_rate"`
	AllowedIndexes            []types.String                       `tfsdk:"allowed_indexes"`
	AuthTokens                []InputSplunkHecAuthTokens           `tfsdk:"auth_tokens"`
	BreakerRulesets           []types.String                       `tfsdk:"breaker_rulesets"`
	CaptureHeaders            types.Bool                           `tfsdk:"capture_headers"`
	Connections               []InputSplunkHecConnections          `tfsdk:"connections"`
	Description               types.String                         `tfsdk:"description"`
	Disabled                  types.Bool                           `tfsdk:"disabled"`
	DropControlFields         types.Bool                           `tfsdk:"drop_control_fields"`
	EmitTokenMetrics          types.Bool                           `tfsdk:"emit_token_metrics"`
	EnableHealthCheck         types.String                         `tfsdk:"enable_health_check"`
	EnableProxyHeader         types.Bool                           `tfsdk:"enable_proxy_header"`
	Environment               types.String                         `tfsdk:"environment"`
	ExtractMetrics            types.Bool                           `tfsdk:"extract_metrics"`
	Host                      types.String                         `tfsdk:"host"`
	ID                        types.String                         `tfsdk:"id"`
	IPAllowlistRegex          types.String                         `tfsdk:"ip_allowlist_regex"`
	IPDenylistRegex           types.String                         `tfsdk:"ip_denylist_regex"`
	KeepAliveTimeout          types.Number                         `tfsdk:"keep_alive_timeout"`
	MaxActiveReq              types.Number                         `tfsdk:"max_active_req"`
	MaxRequestsPerSocket      types.Int64                          `tfsdk:"max_requests_per_socket"`
	Metadata                  []InputSplunkHecMetadata             `tfsdk:"metadata"`
	Pipeline                  types.String                         `tfsdk:"pipeline"`
	Port                      types.Number                         `tfsdk:"port"`
	Pq                        *InputSplunkHecPq                    `tfsdk:"pq"`
	PqEnabled                 types.Bool                           `tfsdk:"pq_enabled"`
	RequestTimeout            types.Number                         `tfsdk:"request_timeout"`
	SendToRoutes              types.Bool                           `tfsdk:"send_to_routes"`
	SocketTimeout             types.Number                         `tfsdk:"socket_timeout"`
	SplunkHecAcks             types.Bool                           `tfsdk:"splunk_hec_acks"`
	SplunkHecAPI              types.String                         `tfsdk:"splunk_hec_api"`
	StaleChannelFlushMs       types.Number                         `tfsdk:"stale_channel_flush_ms"`
	Streamtags                []types.String                       `tfsdk:"streamtags"`
	TLS                       *InputSplunkHecTLSSettingsServerSide `tfsdk:"tls"`
	Type                      types.String                         `tfsdk:"type"`
	UseFwdTimezone            types.Bool                           `tfsdk:"use_fwd_timezone"`
}
