// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputPrometheusRwConnections struct {
	Output   types.String `tfsdk:"output"`
	Pipeline types.String `tfsdk:"pipeline"`
}
