// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputKubeMetricsRules struct {
	Description types.String `tfsdk:"description"`
	Filter      types.String `tfsdk:"filter"`
}
