// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputKubeEvents struct {
	Connections  []InputKubeEventsConnections `tfsdk:"connections"`
	Description  types.String                 `tfsdk:"description"`
	Disabled     types.Bool                   `tfsdk:"disabled"`
	Environment  types.String                 `tfsdk:"environment"`
	ID           types.String                 `tfsdk:"id"`
	Metadata     []InputKubeEventsMetadata    `tfsdk:"metadata"`
	Pipeline     types.String                 `tfsdk:"pipeline"`
	Pq           *InputKubeEventsPq           `tfsdk:"pq"`
	PqEnabled    types.Bool                   `tfsdk:"pq_enabled"`
	Rules        []InputKubeEventsRules       `tfsdk:"rules"`
	SendToRoutes types.Bool                   `tfsdk:"send_to_routes"`
	Streamtags   []types.String               `tfsdk:"streamtags"`
	Type         types.String                 `tfsdk:"type"`
}
