// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputExec struct {
	BreakerRulesets     []types.String         `tfsdk:"breaker_rulesets"`
	Command             types.String           `tfsdk:"command"`
	Connections         []InputExecConnections `tfsdk:"connections"`
	CronSchedule        types.String           `tfsdk:"cron_schedule"`
	Description         types.String           `tfsdk:"description"`
	Disabled            types.Bool             `tfsdk:"disabled"`
	Environment         types.String           `tfsdk:"environment"`
	ID                  types.String           `tfsdk:"id"`
	Interval            types.Number           `tfsdk:"interval"`
	Metadata            []InputExecMetadata    `tfsdk:"metadata"`
	Pipeline            types.String           `tfsdk:"pipeline"`
	Pq                  *InputExecPq           `tfsdk:"pq"`
	PqEnabled           types.Bool             `tfsdk:"pq_enabled"`
	Retries             types.Number           `tfsdk:"retries"`
	ScheduleType        types.String           `tfsdk:"schedule_type"`
	SendToRoutes        types.Bool             `tfsdk:"send_to_routes"`
	StaleChannelFlushMs types.Number           `tfsdk:"stale_channel_flush_ms"`
	Streamtags          []types.String         `tfsdk:"streamtags"`
	Type                types.String           `tfsdk:"type"`
}
