// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OutputFilesystem struct {
	AddIDToStagePath       types.Bool         `tfsdk:"add_id_to_stage_path"`
	AutomaticSchema        types.Bool         `tfsdk:"automatic_schema"`
	BaseFileName           types.String       `tfsdk:"base_file_name"`
	Compress               types.String       `tfsdk:"compress"`
	CompressionLevel       types.String       `tfsdk:"compression_level"`
	DeadletterEnabled      types.Bool         `tfsdk:"deadletter_enabled"`
	DeadletterPath         types.String       `tfsdk:"deadletter_path"`
	Description            types.String       `tfsdk:"description"`
	DestPath               types.String       `tfsdk:"dest_path"`
	EmptyDirCleanupSec     types.Number       `tfsdk:"empty_dir_cleanup_sec"`
	EnablePageChecksum     types.Bool         `tfsdk:"enable_page_checksum"`
	EnableStatistics       types.Bool         `tfsdk:"enable_statistics"`
	EnableWritePageIndex   types.Bool         `tfsdk:"enable_write_page_index"`
	Environment            types.String       `tfsdk:"environment"`
	FileNameSuffix         types.String       `tfsdk:"file_name_suffix"`
	Format                 types.String       `tfsdk:"format"`
	HeaderLine             types.String       `tfsdk:"header_line"`
	ID                     types.String       `tfsdk:"id"`
	KeyValueMetadata       []KeyValueMetadata `tfsdk:"key_value_metadata"`
	MaxFileIdleTimeSec     types.Number       `tfsdk:"max_file_idle_time_sec"`
	MaxFileOpenTimeSec     types.Number       `tfsdk:"max_file_open_time_sec"`
	MaxFileSizeMB          types.Number       `tfsdk:"max_file_size_mb"`
	MaxOpenFiles           types.Number       `tfsdk:"max_open_files"`
	MaxRetryNum            types.Number       `tfsdk:"max_retry_num"`
	OnBackpressure         types.String       `tfsdk:"on_backpressure"`
	OnDiskFullBackpressure types.String       `tfsdk:"on_disk_full_backpressure"`
	ParquetDataPageVersion types.String       `tfsdk:"parquet_data_page_version"`
	ParquetPageSize        types.String       `tfsdk:"parquet_page_size"`
	ParquetRowGroupLength  types.Number       `tfsdk:"parquet_row_group_length"`
	ParquetVersion         types.String       `tfsdk:"parquet_version"`
	PartitionExpr          types.String       `tfsdk:"partition_expr"`
	Pipeline               types.String       `tfsdk:"pipeline"`
	RemoveEmptyDirs        types.Bool         `tfsdk:"remove_empty_dirs"`
	ShouldLogInvalidRows   types.Bool         `tfsdk:"should_log_invalid_rows"`
	StagePath              types.String       `tfsdk:"stage_path"`
	Streamtags             []types.String     `tfsdk:"streamtags"`
	SystemFields           []types.String     `tfsdk:"system_fields"`
	Type                   types.String       `tfsdk:"type"`
	WriteHighWaterMark     types.Number       `tfsdk:"write_high_water_mark"`
}
