// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OutputConfluentCloudKafkaSchemaRegistryAuthentication struct {
	Auth                 *OutputConfluentCloudAuth                                     `tfsdk:"auth"`
	ConnectionTimeout    types.Number                                                  `tfsdk:"connection_timeout"`
	DefaultKeySchemaID   types.Number                                                  `tfsdk:"default_key_schema_id"`
	DefaultValueSchemaID types.Number                                                  `tfsdk:"default_value_schema_id"`
	Disabled             types.Bool                                                    `tfsdk:"disabled"`
	MaxRetries           types.Number                                                  `tfsdk:"max_retries"`
	RequestTimeout       types.Number                                                  `tfsdk:"request_timeout"`
	SchemaRegistryURL    types.String                                                  `tfsdk:"schema_registry_url"`
	TLS                  *OutputConfluentCloudKafkaSchemaRegistryTLSSettingsClientSide `tfsdk:"tls"`
}
