// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OutputNetflowHosts struct {
	Host types.String `tfsdk:"host"`
	Port types.Number `tfsdk:"port"`
}
