// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type OutputGrafanaCloud struct {
	One *OutputGrafanaCloud1 `queryParam:"inline" tfsdk:"one" tfPlanOnly:"true"`
	Two *OutputGrafanaCloud2 `queryParam:"inline" tfsdk:"two" tfPlanOnly:"true"`
}
