// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Samples struct {
	EventsPerSec types.Number `tfsdk:"events_per_sec"`
	Sample       types.String `tfsdk:"sample"`
}
