// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Subscriptions struct {
	BatchTimeout       types.Number                    `tfsdk:"batch_timeout"`
	Compress           types.Bool                      `tfsdk:"compress"`
	ContentFormat      types.String                    `tfsdk:"content_format"`
	HeartbeatInterval  types.Number                    `tfsdk:"heartbeat_interval"`
	Locale             types.String                    `tfsdk:"locale"`
	Metadata           []InputWefSubscriptionsMetadata `tfsdk:"metadata"`
	QuerySelector      types.String                    `tfsdk:"query_selector"`
	ReadExistingEvents types.Bool                      `tfsdk:"read_existing_events"`
	SendBookmarks      types.Bool                      `tfsdk:"send_bookmarks"`
	SubscriptionName   types.String                    `tfsdk:"subscription_name"`
	Targets            []types.String                  `tfsdk:"targets"`
	Version            types.String                    `tfsdk:"version"`
}
